### ISSUE TITLE
[ERROR] PDFPageCountError: Unable to get page count. pdfinfo: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/lib/libpng16.so.16) 

### ISSUE THREAD

**Issue by ghost** [Belval/pdf2image-as-a-service#12]
I get the following error when I try to use pdf2image following your example:

[ERROR] PDFPageCountError: Unable to get page count.
pdfinfo: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/lib/libpng16.so.16)

Traceback (most recent call last):
  File "/var/task/index.py", line 33, in handler
    text = extract_text_pdf(image_path)
  File "/var/task/index.py", line 119, in extract_text_pdf
    imgs = pdf2image.convert_from_path(image_path, output_folder=path)
  File "/opt/python/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 97, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/opt/python/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 471, in pdfinfo_from_path
    raise PDFPageCountError(

**Comment by ghost** [comment]
Sorry, in my case I have fixed by setting 

 poppler_path='/opt/lib/'
